### ISSUE TITLE
An issue on the usage of create_model method in sasctl package

### ISSUE THREAD

**Issue by ownway22** [sassoftware/python-sasctl#138]
**Describe the issue**
In this case, the method we run is **create_model** method under sasctl.services.model_repository class.  

In our customer’s scenario, to define multiple key-value properties with different types as creating a new model object in model repository is necessary.

Is it posssble we can create a model object with user-defined properties which are also having different types?

**To Reproduce**
Steps or example code to reproduce the issue.

**Expected behavior**
With the following document said (shown in Figure 1), the properties parameter is supposed to support that the user can define the desired properties with name, value and type in a array-like format. However, it seems the method doesn’t work like that since its source code only deal with a dictionary object with both name and value only. Which you can check out Figure 2.

**Version**
1.5.4

Figure 1
![figure1](https://user-images.githubusercontent.com/25397165/202942463-26a17a0f-fb9b-4c65-aaa1-17a0d5267366.png)

Figure 2
![figure2](https://user-images.githubusercontent.com/25397165/202942453-0ac5ccfc-448d-4fb7-bf53-bb7392fb1e74.png)

**Comment by jlwalke2** [comment]
Thanks for reporting this.  We've fixed the [create_model()](https://github.com/sassoftware/python-sasctl/blob/7cc3bf37bf8f6024058279a20d8b54e95468a2f8/src/sasctl/_services/model_repository.py#L227) method so that `properties` parameter should be a dictionary of name:value pairs.

The (Python) type of each property value is inspected and the "type" parameter automatically selected.  The "type" names accepted by the REST service are "numeric", "date", "dateTime", and "string".  Any value that doesn't match the first three types is passed as "string".

The change should be included in the next release.
