### ISSUE TITLE
NoneType Session doesn't raise any errors with verify_ssl=False

### ISSUE THREAD

**Issue by smlindauer** [sassoftware/python-sasctl#151]
**Describe the issue**
After "connecting" to a Session with `verify_ssl=False` set in the argument in which the session does **not** create a successful connection to the SAS Viya server, the user is not provided with any indication that the session is actually invalid. Call attempts through sasctl function usage causes `AttributeError: 'NoneType' object has no attribute 'upper'`, traced to sasctl.core.py in version_info line 839. 

**To Reproduce**
Aim a session instance at an http server without specifying `protocol="http"` and setting `verify_ssl=False`. Then attempt any function call that sends an API to the server.

**Expected behavior**
Should we have a check on the Session instance that checks to see if the connection actually exists? Or perhaps a check when it hits the version check step to spit out a warning or error that the session did not properly connect?

**Version**
v1.8.2

**Comment by jlwalke2** [comment]
Fixed in [d0b39ec](https://github.com/sassoftware/python-sasctl/commit/d0b39ecd297a028c6732837a7ae579722de84b7f).

Issue isn't that the session is `None`, it's that the release parsed out of the JSON response is `None`.  The `version_info()` method was making the bad assumption that any good HTTP response would also always include the expected JSON payload.
