### ISSUE TITLE
register_model raised SWATCASActionError

### ISSUE THREAD

**Issue by RobinLiuGP** [sassoftware/python-sasctl#49]
I was following the astore_example.py example in the example folder and ran into an error when trying to register a gradient boosting model. The error message was SWATCASActionError: The action was not successful. I also called swat.astore.describe(model) to make sure that the model itself exists. Do you have any suggestions for troubleshooting?  Thank you.

**Comment by jlwalke2** [comment]
It's difficult to say without knowing more about the exact error.  Can you share the full stack trace?

Registering a model from an ASTORE should only involve calling a few CAS actions: swat.astore.describe and swat.table.save.  It sounds like you've already taken some first steps to debugging - calling these actions directly to make sure they work.  

What were the results of running swat.astore.describe(model)?

**Comment by RobinLiuGP** [comment]
Hi John,

Please find the results of astore.describe ('gbModel_astore') in the attached screenshot.

I then set variable  gbModel = swat_session.CASTable('gbModel_astore'), called register_model(gbModel,project,force = True).

Robin Liu
Data Scientist
CSC Analytics & Decision Analytics
859 Spring St. NW
Atlanta, GA 30308
Mobile: (404) 394-6276

**Comment by jlwalke2** [comment]
Robin, I don't see the screenshot you referenced - can you try uploading it directly to GitHub?

**Comment by RobinLiuGP** [comment]
![sas_describe_astore](https://user-images.githubusercontent.com/59709249/72112175-d2f23680-330a-11ea-9430-46dbf998b022.PNG)

**Comment by RobinLiuGP** [comment]
![sas_describe_astore](https://user-images.githubusercontent.com/59709249/72112282-22d0fd80-330b-11ea-8a5a-e56492354f03.PNG)

**Comment by jlwalke2** [comment]
Looks like the astore exists and you can successfully run the describe action against it, so that's good.

The next potential culprit is the table.save action.  In order to register an astore model you need write access to a specific folder on the server:  /opt/sas/viya/config/data/cas/default/modelStore/
(See the documentation [here](https://go.documentation.sas.com/?docsetId=calmodels&docsetTarget=n0r9qvpxhghjpsn149zfmh0h7qwi.htm&docsetVersion=3.5&locale=en#n16y824ur2d5mpn1kqm11oajn4u2)).  If you're user account doesn't have access, the action will fail.  

You can also test this by running the action manually:
`gbModel.save(name='astore_filename', caslib='ModelStore', replace=True)`

Also, it may have just been a simple copy/paste error, but your `register_model` call above is incorrect:
> register_model(gbModel,project,force = True)

You're missing a parameter for the model name.  It should look something like:
`register_model(gbModel, 'GB Model', project, force = True)`

**Comment by RobinLiuGP** [comment]
It was indeed a permission issue as you suggested, and after granting the right permissions the register_model() method worked. Thank you for your help.

**Comment by jlwalke2** [comment]
Excellent, glad to hear you got it working!
