### ISSUE TITLE
Issues Connecting to Viya

### ISSUE THREAD

**Issue by Xyphi** [sassoftware/python-sasctl#55]
Hi,

I am facing below issue while I try to run  "Session" function to connect to Viya.

![image](https://user-images.githubusercontent.com/60737923/73935515-b1cf3680-4906-11ea-8fa1-ea7407466647.png)

Appreciate your help

**Comment by jlwalke2** [comment]
It looks like the digital certificate that sasctl is trying to use to verify the HTTPS connection couldn't be found.

The `/home/sasdemo/CA/` path is either the system default location or it's been set through an environment variable (see [sasctl environment variables](https://sassoftware.github.io/python-sasctl/#environment-variables)).  To check if this is coming from an environment variable, you can run the code snippet below:
```
import os
for k in ('REQUESTS_CA_BUNDLE', 'SSLCALISTLOC', 'CAS_CLIENT_SSL_CA_LIST'):
    print(k, os.environ.get(k))
```

You need to either change the digital certificate path that sasctl is checking, or you can use the `verify_ssl=False` parameter when creating the `Session` instance.

**Comment by Xyphi** [comment]
> It looks like the digital certificate that sasctl is trying to use to verify the HTTPS connection couldn't be found.
> 
> The `/home/sasdemo/CA/` path is either the system default location or it's been set through an environment variable (see [sasctl environment variables](https://sassoftware.github.io/python-sasctl/#environment-variables)). To check if this is coming from an environment variable, you can run the code snippet below:
> 
> ```
> import os
> for k in ('REQUESTS_CA_BUNDLE', 'SSLCALISTLOC', 'CAS_CLIENT_SSL_CA_LIST'):
>     print(k, os.environ.get(k))
> ```
> 
> You need to either change the digital certificate path that sasctl is checking, or you can use the `verify_ssl=False` parameter when creating the `Session` instance.

Thanks for that. Can you suggest how to locate the digital certificate?

**Comment by jlwalke2** [comment]
It's difficult to say exactly where the digital certificate may be located because it's configurable during the SAS Viya installation.  The default location for httpd on RedHat/CentOS is `/etc/pki/tls/certs`, but you'd have to check with your SAS admin to determine whether the certificate being used by Viya was also installed to that location.

An easier method might be to just download the certificate using your browser.  If you browse to your SAS Viya environment using HTTPS your browser will be presented with a copy of the digital certificate, which you can then download and then point sasctl to it.  See [this link](https://www.shellhacks.com/get-ssl-certificate-from-server-site-url-export-download/) for instructions on how to download certificates using different browsers.

**Comment by Xyphi** [comment]
> It's difficult to say exactly where the digital certificate may be located because it's configurable during the SAS Viya installation. The default location for httpd on RedHat/CentOS is `/etc/pki/tls/certs`, but you'd have to check with your SAS admin to determine whether the certificate being used by Viya was also installed to that location.
> 
> An easier method might be to just download the certificate using your browser. If you browse to your SAS Viya environment using HTTPS your browser will be presented with a copy of the digital certificate, which you can then download and then point sasctl to it. See [this link](https://www.shellhacks.com/get-ssl-certificate-from-server-site-url-export-download/) for instructions on how to download certificates using different browsers.

Thanks for the response. One more query from my end ..... Does sasctl convert python models into DS2 format internally for publishing?

**Comment by jlwalke2** [comment]
Sometimes.  It depends on exactly how you define "convert".

sasctl will automatically try to wrap your Python code in an DS2 envelope so that it can be easily published, but it doesn't actually change any of the underlying Python code/models.  The wrapping simply ensures that the Python model conforms to certain format expectations that SAS has.  This is what's done by tasks like `register_model` and `publish_model`.

However, the `sasctl.utils.pyml2ds` module does provide some utilities that will parse certain Python models and convert them into equivalent DS/DS2.  This functionality does actually replace the Python model with an equivalent SAS model, thus allowing for fully parallel & distributed execution.  Currently, this functionality is not invoked automatically and has to be explicitly called.

So yes, you're correct in that the end result that's published in SAS in a DS2 package, but unless you explicitly ask sasctl to do something different, it will ensure that it's the underlying Python code that's really being executed at the end of the day.
