### ISSUE TITLE
pzmm.writeScoreCode: Variable Name Syntax Error

### ISSUE THREAD

**Issue by smlindauer** [sassoftware/python-sasctl#69]
Referenced from [a duplicate issue on open-model-manager-resources](https://github.com/sassoftware/open-model-manager-resources/issues/15).

The one-hot-encoding used in writeScoreCode.py of the pzmm package needs additional validation before generating variable names. In example, a column titled emp_length which included a value of '< 1 year' tried to create a column named 'emp_length_< 1 year' in the score.py file.

The strip() function at line 176 only removes the leading and trailing spaces. It leaves spaces between characters and special characters, leading to later syntax errors. I would suggest adding uniq =uniq.replace(" ", "_") to replace the spaces with underscores and perhaps using re.sub() from the re package to remove special characters.

**Comment by SophiaRowland** [comment]
@smlindauer 

Hi Scott. I kept playing around with the writeScoreCode.py package and I have some more feedback about the package. 
First, the splitStringColumn() function performing the one-hot-encoding appears to be making assumptions as to what the column names were that the model was trained on, rather than pulling that data from the input data set.  If the model wasn't trained using the same columns and column names, an input error will occur. Additionally, it assumes that inputs will need to be one-hot-encoded and imputed. I created a pipeline that included one-hot-encoding and imputation, which added to the input error since the model was expecting the raw inputs. This data prep is good to have, but I don't think it should be the default all models coming in. 

Second, I had trouble finding where settings.pickle_path is set, but it is used in line 90. We couldn't get this to work and had to push the pickle file into an accessible location and modify the code to call it. Could you explain what is supposed to happen? 

Lastly, the predictMethod input could be a bit cleaner from the user's perspective. '{}.predict_proba({})' is a bit unwieldy as a user input. Additionally, the 'Build and Import a Trained Model into SAS Open Model Manager' example notebook uses '{}.predict({})' for a binary classification model, when it looks like it should have been '{}.predict_proba({})' . 

I am happy to discuss this more if you want to add some time to my calendar.  Thanks!

**Comment by smlindauer** [comment]
@SophiaRowland 

Thanks for the further comments and feedback! I have added a tentative time to discuss this further to our calendars.
