### ISSUE TITLE
predict method returns none value

### ISSUE THREAD

**Issue by kcmrt** [sassoftware/python-sasctl#82]
Hello , 

i have been working on this code , i registered project and model on sas viya later i published model with succesfully  , it works now but when i use MAS to score some new data and it returns none value. 

Can you help me please , how can i solve this problem.

**Comment by smlindauer** [comment]
Hey @kcmrt,

Can you provide more details on the issue:

- What version of SAS Viya are you using?
- Did you use the base sasctl module for registering the project and model or did you leverage the pzmm submodule?
- Did you fail to get an output when publishing to MAS or did you return an error in the log?

**Comment by kcmrt** [comment]
hey @smlindauer ,

version of sas viya is V.03.05. 
I uses sasctl library for registering project and publishing model. 
i didnt get to fail  , it returns only none value. 

At the same time   , I registered another project and published another model on Sas viya later i called the published model using sasctl libray and predict method disappeared. It is very interesting.

**Comment by smlindauer** [comment]
I am not sure this is a sasctl issue then since sasctl successfully pushed the project and model to SAS Model Manager. This sounds like an error in SAS Viya. I would suggest you contact either technical support or post your question on [SAS Communities](https://communities.sas.com/). If you need further help with anything regarding the sasctl module, please post another issue.
