### ISSUE TITLE
update model performance - SWATError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

### ISSUE THREAD

**Issue by nitika-virmani** [sassoftware/python-sasctl#83]
While executing this code, facing issue while executing Last command -update model performance
- step 84 in the notebook.

**Error:**
"SWATError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled."

**Comment by smlindauer** [comment]
Hey @nitika-virmani,

I am not sure what code you are referencing. Do you mind answering the standard "new issue" prompts to better enable us to help you?

**Describe the issue**
A clear and concise description of the issue you're experiencing.

**To Reproduce**
Steps or example code to reproduce the issue.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Stack Trace**
If you're experiencing an exception, include the full stack trace and error message.

**Version**
What version of `sasctl` are you using?

Thanks!

**Comment by jlwalke2** [comment]
@nitika-virmani, as smlindauer noted, we can do a better job diagnosing the issue and assisting you if we're provided more details about the environment and exactly what failed and when.

However, this exception is coming from the [swat](https://github.com/sassoftware/python-swat) package, not `sasctl`.  Without knowing more, my best **guess** is that you're trying to connect to a server that uses SSL but with a self-signed certificate and `swat` is unable to verify the hostname on the digital certificate.  You may be able to get around this error by:

1. using a trusted certificate
2. or try connecting using the FQDN instead of an IP address.

Hopefully that will at least get you on the right path.

**Comment by ChristianGroessinger** [comment]
Hi you have to set the following environmet variable: CAS_CLIENT_SSL_CA_LIST='/path/to/certificates.pem' (path to your trusted certs your (root and intermediate). It should be in .pem format, no .jks, or .p12.
https://sassoftware.github.io/python-swat/encryption.html
