### ISSUE TITLE
Retrieve the unexpected file 

### ISSUE THREAD

**Issue by RoberttsengTAO** [sassoftware/python-sasctl#92]
Hi 
We were trying to retrieve the content like a model pickle file (.pkl) or script file (.py .txt) from a model repository on Viya. With sasctl package (SAS API for python), we always got the unexpected file in a given model project or model name on SAS Model Manager. 
We run into this situation via sasctl package in some scenarios. More concretely, I describe the scenarios step by step respectively below. 
Scenarios 1: 
Two models with the same model name are in two different model projects respectively on SAS Model Manager, then we got unexpected model's UUID  by the function 
```
with Session(host, username, password, verify_ssl=False):
    project_name = "test"
    mm_project = mr.get_project(item = project_name)
    champion_name = mm_project.get('championModelName')
    champion_instance =  mr.get_model(champion_name)
    champion_id = champion_instance.get('id')
    print("Set Project Name: {name}".format(name = project_name))
    print("Get Project's Champion model Name: {name}".format(name = champion_name))
    print('Get champion UUID: {id}'.format(id = champion_id) )
```
![image](https://user-images.githubusercontent.com/34156399/118458641-8eac4d00-b72d-11eb-8ef5-8f7783c18b80.png)

Scenarios 2: 
Two models with different model names are in the same model project on SAS Model Manager and we changed champion model, then we got  an unexpect file by “sasctl.service.get_file_content”
```
    project_name = "test"
    mm_project = mr.get_project(item = project_name)
    champion_name = mm_project.get('championModelName')
    champion_instance =  mr.get_model(champion_name)
    champion_id = champion_instance.get('id')
    file_list = mr.get_model_contents(model= champion_id)
    model_name, model_id, model_fileUri= next(([i.get('name'), i.get('id'), i.get('fileUri')] \
                                               for i in file_list if i.get('name') == filename), None)
    model_obj = files.get_file(model_name)
    model_file = files.get_file_content(model_obj)
    print('Project Name:{name}'.format(name=project_name))
    print('Champion Model Name:{name}'.format(name = champion_name))
    print('Champion Model UUID:{name}'.format(name = champion_id))
    print('model_file_content:{content}'.format(content = model_file))     
```
![image](https://user-images.githubusercontent.com/34156399/118459164-0ed2b280-b72e-11eb-95b4-ff2540c93df7.png) 

Regards
Robert

**Comment by jlwalke2** [comment]
First, thank you for providing such an exceptional level of detail - it made it much easier to reproduce the problem!

Both issues you highlight have to do with stuff sasctl does behind the scenes to try to be helpful, but I'll start by addressing Scenario 1 first:

### Scenario 1

#### Problem
The problem stems from this line of code:
```
champion_instance =  mr.get_model(champion_name)
```
The [REST endpoint](https://developer.sas.com/apis/rest/DecisionManagement/#get-a-model) that's called here actually requires the ID of the model, not the name.  However, retrieving things by name is common, so sasctl tries to be helpful by looking for a model with a matching name if a name is passed instead of an ID.  The problem is that sasctl returns the **first** item that matches the name.  In this case, that happens to be a model that belongs to a separate project.

#### Solution
First, this scenario highlights an issue with sasctl's current behavior; in the next release, we will **add a warning that will notify users** when multiple items matched the same name.

Second, what options are available to ensure that the right model is returned in such scenarios?:

1. A generic option is to use `list_models()` with the `filter=` parameter, which can be used with [filter expressions](https://developer.sas.com/reference/filtering/).  Here's an example of using it to find models while filtering on model name and project name:
```
mr.list_models("and(eq(projectName, 'Project1'), eq(name, 'Decision_tree_samename'))")
```

2. In the case where you're interested in a project's champion model specifically, it may be easier to retrieve the model using "championModel" link on the project:
```
champion_instance = sasctl.request_link(mm_project, 'championModel')
```

### Scenario 2
#### Problem
The problem here is the same as Scenario 1, just with file names instead of model names.  The following line is searching all of Model Manager for *any* file with the name "model.txt":
```
model_obj = files.get_file(model_name)
```
This is problematic because filenames are frequently repeated across models.

#### Solution
If you already have the ID of the object you're looking for, it's always recommended to use that instead of the name.  In this case:
```
model_obj = files.get_file(model_id)
```
Disclaimer:  this approach **should** work, but I was getting `None` results in my test environment.  I will conduct some additional testing to ensure that there's not a bug in the implementation of the Files service, but the general guideline of using ID over name when possible still holds.


Additionally, In this scenario, since you're looking for the file content, there's already a link included in the response from `mr.get_files()` that can be used directly:
```
file_list = mr.get_model_contents(champion_id)
file = next((f for f in file_list if f.name == filename), None)
model_file = sasctl.request_link(file, 'content')
```

**Comment by jlwalke2** [comment]
Warning message added in v1.5.8.

**Comment by jlwalke2** [comment]
Just wanted to add a comment correcting my previous statement that this code should work:
```
model_obj = files.get_file(model_id)
```

This does **not** actually work because the Files service and the Model Repository service use different GUIDs to track files.  You can see this if you look at the IDs in the response:
```
file_list = mr.get_model_contents(model=champion_id)
file = file_list[0]
print(file.id)
print(file.fileUri)
```

> de63d3e0-ea05-4da7-8bf6-150c0438b92e
/files/files/41f5b6c4-965a-46ee-82ab-e5d8d5626bde

The tail end of `fileUri` is the ID assigned to the file by the Files service.  This means that there are a couple of ways to handle this:

1. Use `request_link()` as shown in the example in the previous comment.
2. Request the `fileUri` directly:
```
from sasctl import get
from sasctl.services import files

with Session(...) as s:
    f = get(file.fileUri)                # Returns the file information as stored by Files service
    content = files.get_file_content(f)  # Use Files service to get content
```
3. Parse the `fileUri` value to obtain the ID and then use files.get_file_content(id):
```
from sasctl.services import files

file_id = file.fileUri.split('/')[-1]
files.get_file_content(file_id)
```
